# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
name: 'Next.js Bundle Analysis'

on:
  pull_request:
  push:
    branches:
      # change this if your default branch is named differently
      - main
  workflow_dispatch:

jobs:
  analyze:
    uses: hashicorp/nextjs-bundle-analysis/.github/workflows/analyze.yml@{PACKAGE_VERSION}
    # with:
    #   node-version: 18
    #   package-manager: npm
    #   working-directory: ./
    #   build-command: ./node_modules/.bin/next build
