name: Canary Release

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  release-canary:
    uses: hashicorp/web-platform-packages/.github/workflows/canary-release.yml@69853727452b125f28e777ca7c1e71c82edd30aa
    secrets:
      CHANGESETS_PAT: ${{ secrets.CHANGESETS_PAT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
